logo:
  use_default: 0
  path: themes/contrib/fsu_subtheme/logo/FSU_taglinelockup_stacked_RGB.jpg
brand_image:
  use_default: 1
_core:
  default_config_hash: OhypfKr4_Eo8XwXg3Sios05lN-LjxOhSdSOSkEN9Ndo
